import { Track, Playlist, Album, Artist } from '@/types/audio';

// Demo tracks with sample URLs (you would replace these with real audio URLs)
export const demoTracks: Track[] = [
  {
    id: '1',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    artistId: 'artist1',
    album: 'After Hours',
    albumId: 'album1',
    duration: 200,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    artwork: 'https://picsum.photos/300/300?random=1',
    genre: 'Pop',
    isExplicit: false,
    isLiked: false,
  },
  {
    id: '20',
    title: 'audio stream',
    artist: 'The Weeknd',
    artistId: 'artist1',
    album: 'After Hours',
    albumId: 'album1',
    duration: 200,
    url: 'https://audio.mwonya.com/stream/20250412_5fb72a02fa524c678e1fdbd3e29bf980/playlist.m3u8',
    artwork: 'https://picsum.photos/300/300?random=1',
    genre: 'Pop',
    isExplicit: false,
    isLiked: false,
  },
  {
    id: '2',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    artistId: 'artist2',
    album: '÷ (Divide)',
    albumId: 'album2',
    duration: 233,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    artwork: 'https://picsum.photos/300/300?random=2',
    genre: 'Pop',
    isExplicit: false,
    isLiked: true,
  },
  {
    id: '3',
    title: 'Bad Guy',
    artist: 'Billie Eilish',
    artistId: 'artist3',
    album: 'When We All Fall Asleep, Where Do We Go?',
    albumId: 'album3',
    duration: 194,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    artwork: 'https://picsum.photos/300/300?random=3',
    genre: 'Alternative',
    isExplicit: true,
    isLiked: false,
  },
  {
    id: '4',
    title: 'Someone Like You',
    artist: 'Adele',
    artistId: 'artist4',
    album: '21',
    albumId: 'album4',
    duration: 285,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    artwork: 'https://picsum.photos/300/300?random=4',
    genre: 'Soul',
    isExplicit: false,
    isLiked: true,
  },
  {
    id: '5',
    title: 'Watermelon Sugar',
    artist: 'Harry Styles',
    artistId: 'artist5',
    album: 'Fine Line',
    albumId: 'album5',
    duration: 174,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    artwork: 'https://picsum.photos/300/300?random=5',
    genre: 'Pop Rock',
    isExplicit: false,
    isLiked: false,
  },
  {
    id: '6',
    title: 'Good 4 U',
    artist: 'Olivia Rodrigo',
    artistId: 'artist6',
    album: 'SOUR',
    albumId: 'album6',
    duration: 178,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    artwork: 'https://picsum.photos/300/300?random=6',
    genre: 'Pop Punk',
    isExplicit: false,
    isLiked: true,
  },
  {
    id: '7',
    title: 'Industry Baby',
    artist: 'Lil Nas X ft. Jack Harlow',
    artistId: 'artist7',
    album: 'MONTERO',
    albumId: 'album7',
    duration: 212,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    artwork: 'https://picsum.photos/300/300?random=7',
    genre: 'Hip Hop',
    isExplicit: true,
    isLiked: false,
  },
  {
    id: '8',
    title: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    artistId: 'artist8',
    album: 'Stay',
    albumId: 'album8',
    duration: 141,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    artwork: 'https://picsum.photos/300/300?random=8',
    genre: 'Pop',
    isExplicit: false,
    isLiked: true,
  },
];

export const demoArtists: Artist[] = [
  {
    id: 'artist1',
    name: 'The Weeknd',
    avatar: 'https://picsum.photos/200/200?random=11',
    bio: 'Canadian singer, songwriter, and record producer.',
    isVerified: true,
    monthlyListeners: 85000000,
  },
  {
    id: 'artist2',
    name: 'Ed Sheeran',
    avatar: 'https://picsum.photos/200/200?random=12',
    bio: 'English singer-songwriter, musician, record producer, and actor.',
    isVerified: true,
    monthlyListeners: 75000000,
  },
  {
    id: 'artist3',
    name: 'Billie Eilish',
    avatar: 'https://picsum.photos/200/200?random=13',
    bio: 'American singer and songwriter.',
    isVerified: true,
    monthlyListeners: 65000000,
  },
  {
    id: 'artist4',
    name: 'Adele',
    avatar: 'https://picsum.photos/200/200?random=14',
    bio: 'English singer-songwriter.',
    isVerified: true,
    monthlyListeners: 45000000,
  },
  {
    id: 'artist5',
    name: 'Harry Styles',
    avatar: 'https://picsum.photos/200/200?random=15',
    bio: 'English singer, songwriter, and actor.',
    isVerified: true,
    monthlyListeners: 55000000,
  },
  {
    id: 'artist6',
    name: 'Olivia Rodrigo',
    avatar: 'https://picsum.photos/200/200?random=16',
    bio: 'American singer-songwriter and actress.',
    isVerified: true,
    monthlyListeners: 70000000,
  },
];

export const demoAlbums: Album[] = [
  {
    id: 'album1',
    title: 'After Hours',
    artist: 'The Weeknd',
    artistId: 'artist1',
    artwork: 'https://picsum.photos/300/300?random=21',
    releaseDate: new Date('2020-03-20'),
    tracks: demoTracks.filter(t => t.albumId === 'album1'),
    genre: 'Pop',
  },
  {
    id: 'album2',
    title: '÷ (Divide)',
    artist: 'Ed Sheeran',
    artistId: 'artist2',
    artwork: 'https://picsum.photos/300/300?random=22',
    releaseDate: new Date('2017-03-03'),
    tracks: demoTracks.filter(t => t.albumId === 'album2'),
    genre: 'Pop',
  },
  {
    id: 'album3',
    title: 'When We All Fall Asleep, Where Do We Go?',
    artist: 'Billie Eilish',
    artistId: 'artist3',
    artwork: 'https://picsum.photos/300/300?random=23',
    releaseDate: new Date('2019-03-29'),
    tracks: demoTracks.filter(t => t.albumId === 'album3'),
    genre: 'Alternative',
  },
];

export const demoPlaylists: Playlist[] = [
  {
    id: 'playlist1',
    name: 'Top Hits 2024',
    description: 'The biggest hits of the year',
    artwork: 'https://picsum.photos/300/300?random=31',
    tracks: demoTracks.slice(0, 5),
    isPublic: true,
    createdBy: 'user1',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'playlist2',
    name: 'Chill Vibes',
    description: 'Relax and unwind with these mellow tracks',
    artwork: 'https://picsum.photos/300/300?random=32',
    tracks: demoTracks.slice(2, 6),
    isPublic: true,
    createdBy: 'user1',
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'playlist3',
    name: 'Workout Mix',
    description: 'High energy songs to keep you motivated',
    artwork: 'https://picsum.photos/300/300?random=33',
    tracks: demoTracks.slice(1, 4),
    isPublic: false,
    createdBy: 'user1',
    createdAt: new Date('2024-03-01'),
  },
];

// Featured content for home page
export const featuredContent = {
  hero: {
    title: 'Welcome to Your Music',
    subtitle: 'Discover new music, create playlists, and enjoy your favorite tracks',
    backgroundImage: 'https://picsum.photos/1200/600?random=100',
  },
  newReleases: demoAlbums.slice(0, 3),
  trendingTracks: demoTracks.slice(0, 6),
  featuredPlaylists: demoPlaylists,
  topArtists: demoArtists.slice(0, 6),
};

// Search suggestions
export const searchSuggestions = [
  'The Weeknd',
  'Billie Eilish',
  'Pop music',
  'New releases',
  'Top hits',
  'Chill',
  'Workout',
  'Rock',
  'Hip Hop',
  'Jazz',
];